[WIP] Feature/breakdown
EQWorks/vz pull request #4
Opened 2018-08-14 21:34 UTC by y629wang

2018-08-28 04:57 UTC, woozyking requested changes

2018-08-28 04:57 UTC, woozyking commented on demo/app.js
> +    {false && <BreakdownContainer />}
Just remove them altogether since now this demo is consolidated into `ScatterPieContainer` (but maybe rename it to `BreakdownContainer`)

2018-08-28 04:57 UTC, woozyking commented on src/visualizations/index.js
> +export { default as ScatterPie } from './scatter-pie'
Please update `.eslintrc.js` with the following content and run `npm run lint -- --fix` to fix both new line at the end of file and dangling comma for multiline objects/arrays and alike:

```js
module.exports = {
  "env": {
    "browser": true,
    "es6": true,
  },
  "extends": [
    "eslint:recommended",
    "plugin:react/recommended",
  ],
  "parser": "babel-eslint",
  "parserOptions": {
    ecmaVersion: 6,
    "sourceType": "module",
  },
  "plugins": [
    "react",
  ],
  "rules": {
    "indent": [
      "error",
      2,
    ],
    "linebreak-style": [
      "error",
      "unix",
    ],
    "quotes": [
      "error",
      "single",
    ],
    "semi": [
      "error",
      "never",
    ],
    "no-console": [
      "warn",
    ],
    "comma-dangle": [
      "error",
      "always-multiline",
    ],
    "eol-last": [
      "error",
      "always",
    ],
  },
}
```

2018-08-28 04:57 UTC, woozyking commented on src/visualizations/scatter-pie.js
> +  if (width < 10) return null
shall we apply `NoSpace` for this, with a much larger minimum width than 10?

2018-08-28 04:57 UTC, woozyking commented on src/visualizations/scatter-pie.js
> +            {`Sub-category ${kGetter(tooltipData.data)}: ${vGetter(tooltipData.data)}`}
Can we either remove the phrase `Sub-category` or make it configurable?

2018-09-05 16:23 UTC, woozyking approved these changes

2018-09-05 21:05 UTC, brianbancroft requested changes
This is just my first glance. I'll also give it a run-through as well.

2018-09-05 21:05 UTC, brianbancroft commented on src/visualizations/scatter-pie.js
> +      <React.Fragment key={Math.random()}>
I feel like this would be a memory hog https://stackoverflow.com/questions/29808636/when-giving-unique-keys-to-components-is-it-okay-to-use-math-random-for-gener

2018-09-05 21:05 UTC, brianbancroft commented on src/visualizations/scatter-pie.js
> +          key={`pie-${i}`}
:+1:

2018-09-05 21:09 UTC, woozyking commented on src/visualizations/scatter-pie.js
> +      <React.Fragment key={Math.random()}>
This is my fault, as I directly copied this from the official vx example

https://vx-demo.now.sh/static/docs/vx-tooltip.html

2018-09-05 21:10 UTC, woozyking commented on src/visualizations/scatter-pie.js
> +      <React.Fragment key={Math.random()}>
Or https://codesandbox.io/s/kw02m019mr at line 66

2018-09-07 16:57 UTC, brianbancroft approved these changes

2018-09-07 18:28 UTC, merged